### ISSUE TITLE
Client wants to blacklist several URLs and also wants POST PUT and DELETE but not get

### ISSUE THREAD

**Issue by lorynwilliams1** [acoustic-analytics/UICaptureSDK-Modules#1]
Can this be done?
All examples have just one URL or one negative condition.
The old Ajax listener could blacklist URLs, can this one?

**Comment by mpunjabi-ibm** [comment]
See [this example](https://github.com/ibm-watson-cxa/UICaptureSDK-Modules/tree/master/AjaxListener#logging-all-xhr-requests-except-those-made-to-the-ibm-cloud) in the README for an example of a blacklist.

**Comment by lorynwilliams1** [comment]
I was looking for more than one URL in the example.
Finally figured it out
url: { regex: "^webapi$|webapi\/(?!cache)|webapi\/(?!feedback)|webapi\/(?!guestAuth\/authorize).*", flags: "i" },
