### ISSUE TITLE
Cannot set property 'end' of undefined errors for older versions of Chrome and Samsung Browser

### ISSUE THREAD

**Issue by rgiancol** [acoustic-analytics/UICaptureSDK-Modules#10]
We recently deployed this module to our production website and it started logging thousands of "Cannot set property 'end' of undefined" errors in our logs.  Further investigation showed that the error was enough to block users from continuing on the site.  I was able to trace the issue back to some really old browser versions.  Predominantly users with Chrome 30x and Samsung browser 2.x.  

We are using SDK 5.6 with all add-on modules disabled and useFetch: true.  

Observation:  At first glance, it may be an unexpected condition for earlier versions of Chrome and Samsung that do not support fetch.

**Comment by mpunjabi-aco** [comment]
1. What is the [AjaxListener module version](https://github.com/ibm-watson-cxa/UICaptureSDK-Modules/tree/master/AjaxListener#module-version) you've deployed?
2. Does your application use fetch, XHR or both?
3. Is there a publicly accessible link for the application/website?

**Comment by mpunjabi-aco** [comment]
Resolved in module version 1.2.2
