### ISSUE TITLE
Works on every browser?

### ISSUE THREAD

**Issue by agarridob** [acoustic-analytics/UICaptureSDK-Modules#4]
I remember with the old version (ajaxIntercept) it was necessary to check wether the browser was not IE or Safari (old).
Is this still mandatory or can it be set active to every user?

**Comment by mpunjabi-ibm** [comment]
Browser support is the same as [UIC 5.5.0](https://developer.ibm.com/customer-engagement/docs/watson-marketing/ibm-watson-customer-experience-analytics/tealeaf-ui-capture/demo-page-saw/#sup%20browser)

This module can be active regardless of the browser although it will not provide any value on browsers that do not implement XMLHttpRequest.

To disable this specific module at runtime, set the `enabled` property to false in the [UIC configuration](https://github.com/ibm-watson-cxa/UICaptureSDK-Modules/tree/master/AjaxListener#configuration)
