### ISSUE TITLE
Original and request URLs formatted strangely

### ISSUE THREAD

**Issue by quackdor** [acoustic-analytics/UICaptureSDK-Modules#6]
Not sure if this is just when a port number is included or if it's something specific to our environment but it seems the slash between the URL an URI portions of the original and request URLs is missing.  When viewing headers in developer tools none are presented in this way.  It is captured correctly for the "description" field
"originalURL": "api-gw.cigna.com:443my/curated-moments/v1/curated-moments",
"requestURL": "api-gw.cigna.com:443my/curated-moments/v1/curated-moments",
"description": "Full Ajax Monitor https://api-gw.cigna.com/my/curated-moments/v1/curated-moments?_ts=1565615981924",

**Comment by cherry-czhang** [comment]
This is an unhandled case in IE browser. We will provide fix in next update.
