### ISSUE TITLE
Incorrect status code for timed out HXR calls

### ISSUE THREAD

**Issue by quackdor** [acoustic-analytics/UICaptureSDK-Modules#7]
Ajax listener records status code of 0 when status of 504 was observed in developer tools of the browser.

**Comment by agarridob** [comment]
I can see this happening in every version, up to 1.1.4

**Comment by mpunjabi-ibm** [comment]
The browser may be timing out the request before the server timeout occurs which would explain why the client side code receives a status 0 whereas the (later) server response is 504.

Can you provide the steps to reproduce this issue?

**Comment by quackdor** [comment]
It's mostly page load and page transitions on a secure single page app.

**Comment by mpunjabi-aco** [comment]
Closing as the issue is not reproducible.
