### ISSUE TITLE
Uncaught TypeError: Cannot read property 'body' of undefined at window.fetch

### ISSUE THREAD

**Issue by whbird** [acoustic-analytics/UICaptureSDK-Modules#9]
Getting syntax error when testing the new ajax listener 1.2.0 with fetch support.  In my test page I make a fetch request to 404 missing JSON file but 1.2.0 throws this error:  AcousticExperience(TL)UIC-CLIENT-servicesTemplate.js:79 Uncaught TypeError: Cannot read property 'body' of undefined at window.fetch (https://127.0.0.1/tealeaf-libs/AcousticTealeaf_UICaptureSDK_5.6.0/AcousticExperience(TL)UIC-CLIENT-servicesTemplate.js:79:4638)

That is line "if (B.body) {" in the chrome-prettyprinted source of ajax listener:      

function i() {
        p = window.fetch;
        window.fetch = function(C, B) {
            var A = {}, D;
            if (typeof C === "object") {
                A.initData = C;
                A.url = C.url;
                A.initData.clone().text().then(function(E) {
                    if (E.length > 0) {
                        A.body = E
                    }
                })
            } else {
                A.initData = B || {};
                A.url = C;
                if (B.body) {                     
			A.body = B.body
                }
            }

If I comment out the 1.2.0 ajax listener, UIC works OK and I see my fetch 404 result:    
Request URL: https://127.0.0.1/tealeaf-libs/AcousticTealeaf_UICaptureSDK_5.6.0/doesnotexist.json
Request Method: GET
Status Code: 404 Not Found

here's the fetch I am making in my test page:

fetch('https://127.0.0.1/tealeaf-libs/AcousticTealeaf_UICaptureSDK_5.6.0/doesnotexist.json')
		.then((response) => {
		return response.json();
	})
	.then((data) => {
		console.log(data);
	});

Here's my test session showing the error:

https://us.tealeaf.ibmcloud.com/webapp/home#/session-replay-timeline?org=tealeaf-com&sid=67765520185409338299540974149729_20200306095828&tltsid=67765520185409338299540974149729&saved=false&reportName=Report&appKey=2508cb55cf0a4b94be3d2679275b1c61

![Ajaxlistener1 2 0_error_20200306](https://user-images.githubusercontent.com/52763992/76128767-e21ff880-5fca-11ea-9c9e-cefe4ce4e0ae.png)

**Comment by cherry-czhang** [comment]
This issue is addressed in 'v1.2.1'.
